#!/bin/bash

export GOPATH=${PWD}
export CGO_ENABLED=0
export GOOS=linux

go build -a -ldflags "-X main.GitCommitId=$GIT_COMMIT -extldflags "-static"" -o bin/`uname -m`/sriov sriov
file bin/`uname -m`/sriov

go build -a -ldflags "-X main.GitCommitId=$GIT_COMMIT -extldflags "-static"" -o bin/`uname -m`/fixipam fixipam
file bin/`uname -m`/fixipam
